json.id post.id
json.box_id post.box_id
json.user_name post.user.name
json.user_image post.user.image
json.box_name post.box.name
json.box_image post.box.image
json.content post.content
json.images post.images
json.mini_program post.mini_program
json.parent_id post.parent_id
json.parent_box_id post.parent_box_id
json.parent_box_name post.parent_box_name
json.last_shared_at post.last_shared_at
json.created_at post.created_at
json.updated_at post.updated_at
