json.id user.id
json.name user.name
json.image user.image
json.gender user.gender
json.country user.country
json.province user.province
json.city user.city
json.language user.language
json.forbidden user.forbidden
json.role user.role
json.badge user.badge
json.balance user.balance.amount
json.total_profit user.balance.total_profit
json.total_withdraw user.balance.total_withdraw
json.fee_rate user.balance.fee_rate
json.created_at user.created_at
